/**
 * Zentrale Beratungsthemen – Faktenquelle für advice_question (keine Einzel-Regex pro Frage).
 */
export const ADVICE_TOPIC_IDS = {
  HEAT_PUMP: 'heat_pump',
  EV_TOWING_RANGE: 'ev_towing_range',
  WINTER_RANGE: 'winter_range',
  BATTERY_SIZE: 'battery_size',
  ALL_WHEEL_DRIVE: 'all_wheel_drive',
  HOME_CHARGING: 'home_charging',
  LEASING_VS_FINANCING: 'leasing_vs_financing',
  HYBRID_VS_PLUGIN: 'hybrid_vs_plugin_hybrid',
  TRAILER_LOAD: 'trailer_load',
  LONG_DISTANCE_TRAVEL: 'long_distance_travel',
  FAMILY_LUGGAGE: 'family_luggage',
  CHARGING_SPEED: 'charging_speed',
  V2L: 'v2l_bidirectional',
};

export const ADVICE_TOPICS = [
  {
    id: ADVICE_TOPIC_IDS.HEAT_PUMP,
    label: 'Wärmepumpe bei Elektroautos',
    featureId: 'heat_pump',
    triggerExamples: [
      'Warum sollte ich eine Wärmepumpe nehmen?',
      'Wofür ist eine Wärmepumpe gut?',
      'Brauche ich eine Wärmepumpe?',
      'Was bringt eine Wärmepumpe?',
      'Lohnt sich eine Wärmepumpe?',
      'Mit oder ohne Wärmepumpe?',
    ],
    keywords: ['wärmepumpe', 'waermepumpe', 'heizstab'],
    shortAnswer: 'Eine Wärmepumpe nutzt Umgebungswärme und spart im Winter oft Reichweite gegenüber reiner Heizstab-Heizung.',
    usefulWhen: [
      'Sie fahren viel im Winter oder auf längeren Strecken.',
      'Reichweite bei Kälte ist Ihnen wichtig.',
      'Sie laden zuhause oder unterwegs regelmäßig.',
    ],
    lessImportantWhen: ['Kurzstrecke und mildes Klima überwiegen.'],
    dealerCheckHint: 'Ihr Autohaus prüft, ob Ihr Wunschmodell die Wärmepumpe serienmäßig oder optional bietet.',
    dealerChecks: ['passendes Modell und Ausstattungslinie', 'Verfügbarkeit im Bestand', 'Reichweite im Winter für Ihren Alltag'],
    relatedQuestions: [{ id: 'winter_range', label: 'Reichweite im Winter', query: 'Wie stark sinkt die Reichweite im Winter?' }],
    relatedDataNeeds: ['trimFeatureMapping', 'heat_pump'],
    needsDealerCheck: false,
    ctaLabel: 'Verkäufer dazu fragen',
  },
  {
    id: ADVICE_TOPIC_IDS.EV_TOWING_RANGE,
    label: 'Reichweite mit Anhänger',
    featureId: 'towbar',
    triggerExamples: [
      'Wie weit kann ich mit einem Elektroauto meinen Anhänger ziehen?',
      'Wie weit komme ich mit Wohnwagen?',
      'E-Auto mit Anhänger Reichweite',
      'Reichweite beim Ziehen',
      'Anhänger mit Elektroauto',
    ],
    keywords: ['anhänger', 'anhaenger', 'wohnwagen', 'ziehen', 'schleppen', 'reichweite'],
    shortAnswer: 'Mit Anhänger sinkt die Reichweite bei Elektroautos deutlich. Wie stark, hängt vor allem von Gewicht, Form des Anhängers, Tempo, Wetter und Strecke ab.',
    usefulWhen: [
      'Anhängelast des Fahrzeugs prüfen',
      'Anhängergewicht und Zuladung kennen',
      'Luftwiderstand und Tempo beachten',
      'Reichweite mit Reserve planen',
      'Ladeplanung auf der Urlaubsstrecke',
    ],
    lessImportantWhen: ['Sie ziehen nur selten oder kurze Strecken ohne Anhänger.'],
    dealerCheckHint: 'Ihr Autohaus kann anhand Ihres Anhängers und Wunschmodells genauer einschätzen, was realistisch ist.',
    dealerChecks: ['passendes Modell', 'reale Anhängelast', 'Reichweite mit Ihrem Anhänger', 'Angebot und Verfügbarkeit'],
    relatedQuestions: [{ id: 'trailer_load', label: 'Anhängelast', query: 'Welcher Kia zieht am meisten?' }],
    relatedDataNeeds: ['towing', 'wltp_range'],
    needsDealerCheck: true,
    ctaLabel: 'Verkäufer dazu fragen',
    secondaryCtaLabel: 'Anhänger-Daten senden',
  },
  {
    id: ADVICE_TOPIC_IDS.WINTER_RANGE,
    label: 'Reichweite im Winter',
    featureId: 'heat_pump',
    triggerExamples: ['Wie stark sinkt die Reichweite im Winter?', 'Reichweite im Winter', 'Winter Reichweite Elektroauto'],
    keywords: ['winter', 'kälte', 'kaelte', 'reichweite', 'sinkt'],
    shortAnswer: 'Kälte reduziert die Reichweite bei Elektroautos – das ist normal. Oft sind es im Alltag 15–25 % weniger als der WLTP-Wert.',
    usefulWhen: ['Vorklimatisierung beim Laden nutzen', 'Wärmepumpe kann helfen', 'Reserve bei Langstrecke einplanen'],
    lessImportantWhen: ['Garage und kurze Pendelstrecken dominieren.'],
    dealerCheckHint: 'Ihr Autohaus kann Modell und Ausstattung für Ihren Winteralltag einordnen.',
    dealerChecks: ['Reichweite WLTP', 'Wärmepumpe', 'Verfügbarkeit'],
    relatedQuestions: [],
    relatedDataNeeds: ['wltp_range', 'heat_pump'],
    needsDealerCheck: false,
    ctaLabel: 'Verkäufer dazu fragen',
  },
  {
    id: ADVICE_TOPIC_IDS.BATTERY_SIZE,
    label: 'Batteriegröße einschätzen',
    triggerExamples: ['Reicht eine kleine Batterie?', 'Was bringt eine große Batterie?', 'Batteriegröße Elektroauto'],
    keywords: ['batterie', 'akku', 'kwh', 'kleine batterie', 'große batterie', 'reicht'],
    shortAnswer: 'Kurze Pendelstrecken: kompaktere Batterie kann reichen. Vielfahrer und Urlaub profitieren oft von mehr Kapazität.',
    usefulWhen: ['Tägliche Strecke realistisch einschätzen', 'Lademöglichkeiten zuhause und unterwegs', 'Urlaubsfahrten mit einplanen'],
    lessImportantWhen: ['Sie laden täglich und fahren wenig.'],
    dealerCheckHint: 'Ihr Autohaus vergleicht Batterievarianten mit Ihrem Fahrprofil.',
    dealerChecks: ['Batterieoptionen', 'Reichweite', 'Preis/Leasing'],
    relatedQuestions: [],
    relatedDataNeeds: ['battery', 'wltp_range'],
    needsDealerCheck: false,
    ctaLabel: 'Verkäufer dazu fragen',
  },
  {
    id: ADVICE_TOPIC_IDS.ALL_WHEEL_DRIVE,
    label: 'Allrad – wann sinnvoll?',
    featureId: 'awd',
    triggerExamples: ['Was bringt Allrad?', 'Brauche ich Allrad?', 'Allrad sinnvoll'],
    keywords: ['allrad', '4x4', 'awd', 'schnee'],
    shortAnswer: 'Allrad hilft bei Schnee, Steigung und unbefestigten Wegen. Für reine Pendlerstrecken reicht oft Frontantrieb.',
    usefulWhen: ['Schnee und Bergregion', 'Stallung und Anfahrhilfe'],
    lessImportantWhen: ['Überwiegend Stadt und Autobahn.'],
    dealerCheckHint: 'Ihr Autohaus zeigt Modelle mit und ohne Allrad.',
    dealerChecks: ['Allrad-Modelle', 'Verfügbarkeit', 'Mehrverbrauch'],
    relatedQuestions: [],
    relatedDataNeeds: ['awd'],
    needsDealerCheck: false,
    ctaLabel: 'Verkäufer dazu fragen',
  },
  {
    id: ADVICE_TOPIC_IDS.HOME_CHARGING,
    label: 'Laden zuhause',
    triggerExamples: ['Wie lade ich zuhause?', 'Wallbox zuhause', 'Laden in der Garage'],
    keywords: ['wallbox', 'zuhause', 'garage', 'laden'],
    shortAnswer: 'Zuhause laden ist oft am günstigsten und bequemsten. Wallbox, Stromtarif und Hausinstallation sollten zusammenpassen.',
    usefulWhen: ['Eigener Stellplatz oder Garage', 'Regelmäßige Nutzung über Nacht'],
    lessImportantWhen: ['Nur öffentliches Laden möglich.'],
    dealerCheckHint: 'Ihr Autohaus berät zu Wallbox, Förderung und passenden Modellen.',
    dealerChecks: ['Wallbox-Angebot', 'Ladeleistung Fahrzeug', 'Installation'],
    relatedQuestions: [],
    relatedDataNeeds: ['charging'],
    needsDealerCheck: true,
    ctaLabel: 'Verkäufer dazu fragen',
  },
  {
    id: ADVICE_TOPIC_IDS.LEASING_VS_FINANCING,
    label: 'Leasing oder Finanzierung?',
    triggerExamples: ['Ist Leasing oder Finanzierung besser?', 'Leasing oder Finanzierung', 'Kauf oder Leasing'],
    keywords: ['leasing', 'finanzierung', 'kauf', 'rate'],
    shortAnswer: 'Leasing: feste Rate und planbare Laufzeit. Finanzierung: Eigentum am Ende. Die passende Form hängt von Laufzeit, Kilometern und Steuer ab.',
    usefulWhen: ['Planbare monatliche Belastung', 'Klare Laufzeit'],
    lessImportantWhen: ['Langfristiger Besitz ohne Kilometerlimit.'],
    dealerCheckHint: 'Ihr Autohaus rechnet beide Varianten mit Ihren Konditionen durch.',
    dealerChecks: ['Leasingrate', 'Finanzierung', 'Sonderzahlung'],
    relatedQuestions: [],
    relatedDataNeeds: ['pricing'],
    needsDealerCheck: true,
    ctaLabel: 'Verkäufer dazu fragen',
  },
  {
    id: ADVICE_TOPIC_IDS.HYBRID_VS_PLUGIN,
    label: 'Hybrid oder Plug-in-Hybrid?',
    triggerExamples: ['Was ist besser Hybrid oder Plug-in-Hybrid?', 'Hybrid oder Plug-in-Hybrid', 'PHEV oder Hybrid'],
    keywords: ['hybrid', 'plug-in', 'plugin', 'phev'],
    shortAnswer: 'Plug-in-Hybrid: elektrische Alltagsstrecke mit Lademöglichkeit. Vollhybrid: kein Stecker nötig, weniger E-Reichweite.',
    usefulWhen: ['Kurzstrecke elektrisch fahren', 'Stecker zuhause'],
    lessImportantWhen: ['Selten laden oder nur Langstrecke.'],
    dealerCheckHint: 'Ihr Autohaus vergleicht Hybrid-Modelle mit Ihrem Fahrprofil.',
    dealerChecks: ['Reichweite elektrisch', 'Verbrauch', 'Modelle im Bestand'],
    relatedQuestions: [],
    relatedDataNeeds: ['powertrain'],
    needsDealerCheck: true,
    ctaLabel: 'Verkäufer dazu fragen',
  },
  {
    id: ADVICE_TOPIC_IDS.TRAILER_LOAD,
    label: 'Anhängelast',
    featureId: 'towbar',
    triggerExamples: ['Wie viel darf ich ziehen?', 'Anhängelast Elektroauto'],
    keywords: ['anhängelast', 'anhaengelast', 'zuglast', 'tonnen'],
    shortAnswer: 'Die zulässige Anhängelast hängt vom konkreten Modell und der Ausstattung ab – nicht alle E-Autos sind gleich.',
    usefulWhen: ['Gebremste und ungebremste Last unterscheiden', 'Modell und Linie prüfen'],
    lessImportantWhen: [],
    dealerCheckHint: 'Ihr Autohaus nennt die Anhängelast für Ihr Wunschmodell.',
    dealerChecks: ['Anhängelast WLTP/Hersteller', 'AHK-Verfügbarkeit'],
    relatedQuestions: [{ id: 'ev_towing_range', label: 'Reichweite mit Anhänger', query: 'Wie weit komme ich mit Anhänger?' }],
    relatedDataNeeds: ['towing'],
    needsDealerCheck: false,
    ctaLabel: 'Verkäufer dazu fragen',
  },
  {
    id: ADVICE_TOPIC_IDS.LONG_DISTANCE_TRAVEL,
    label: 'E-Auto in den Urlaub',
    triggerExamples: ['Kann ich mit einem E-Auto in den Urlaub fahren?', 'E-Auto Urlaub fahren', 'Langstrecke Elektroauto'],
    keywords: ['urlaub', 'reisen', 'langstrecke', 'fernfahrt'],
    shortAnswer: 'Ja – mit Planung. Entscheidend sind Reichweite, Ladeleistung, Reserven und die Ladeinfrastruktur auf der Route.',
    usefulWhen: ['Ladeplan mit Schnellladern', 'Reserve bei Kälte und Tempo', 'Größere Batterie oder Zwischenladen'],
    lessImportantWhen: ['Nur Kurzstrecke.'],
    dealerCheckHint: 'Ihr Autohaus empfiehlt Modelle für Ihre typische Urlaubsroute.',
    dealerChecks: ['Reichweite', 'DC-Laden', 'Bestand'],
    relatedQuestions: [],
    relatedDataNeeds: ['wltp_range', 'charging'],
    needsDealerCheck: true,
    ctaLabel: 'Verkäufer dazu fragen',
  },
  {
    id: ADVICE_TOPIC_IDS.FAMILY_LUGGAGE,
    label: 'Platz für Familie & Gepäck',
    triggerExamples: ['Reicht der Kofferraum für Familie?', 'Kinderwagen Kofferraum'],
    keywords: ['kofferraum', 'familie', 'kinderwagen', 'platz'],
    shortAnswer: 'Für Familie zählen Kofferraumvolumen, Sitze und praktische Details wie ISOFIX und Ladekante.',
    usefulWhen: ['Kinderwagen oder Hundebox', 'Mehrere Sitze'],
    lessImportantWhen: [],
    dealerCheckHint: 'Ihr Autohaus zeigt passende Modelle im Showroom oder Bestand.',
    dealerChecks: ['Kofferraum Liter', 'Sitze', 'Verfügbarkeit'],
    relatedQuestions: [],
    relatedDataNeeds: ['trunk_volume', 'seats'],
    needsDealerCheck: false,
    ctaLabel: 'Verkäufer dazu fragen',
  },
  {
    id: ADVICE_TOPIC_IDS.CHARGING_SPEED,
    label: 'Ladegeschwindigkeit',
    triggerExamples: ['Wie schnell lädt ein E-Auto?', 'Schnellladen DC', 'Ladeleistung kW'],
    keywords: ['schnelllad', 'ladeleistung', 'dc', 'kw'],
    shortAnswer: 'Die Ladegeschwindigkeit hängt von Fahrzeug, Batterietemperatur und Ladestation ab – Peak-kW ist nicht der Durchschnitt.',
    usefulWhen: ['DC-Schnellladen auf Langstrecke', 'Akku-Größe'],
    lessImportantWhen: ['Nur AC zuhause.'],
    dealerCheckHint: 'Ihr Autohaus erklärt Ladeleistung für Ihr Wunschmodell.',
    dealerChecks: ['DC-kW', 'AC-kW', 'Modellvariante'],
    relatedQuestions: [],
    relatedDataNeeds: ['charging'],
    needsDealerCheck: false,
    ctaLabel: 'Verkäufer dazu fragen',
  },
  {
    id: ADVICE_TOPIC_IDS.V2L,
    label: 'Vehicle-to-Load (V2L)',
    featureId: 'v2l',
    triggerExamples: ['Was ist V2L?', 'Strom aus dem Auto', 'Vehicle to Load'],
    keywords: ['v2l', 'vehicle to load', 'bidirektional', 'steckdose'],
    shortAnswer: 'V2L erlaubt, Geräte über das E-Auto zu betreiben. Verfügbarkeit und Leistung sind modellabhängig.',
    usefulWhen: ['Camping', 'Werkzeug unterwegs', 'Notstrom'],
    lessImportantWhen: [],
    dealerCheckHint: 'Ihr Autohaus prüft V2L beim Wunschmodell.',
    dealerChecks: ['V2L-Verfügbarkeit', 'Adapter', 'Leistung'],
    relatedQuestions: [],
    relatedDataNeeds: ['v2l'],
    needsDealerCheck: false,
    ctaLabel: 'Verkäufer dazu fragen',
  },
];

const LEGACY_TOPIC_MAP = {
  heat_pump_benefit: ADVICE_TOPIC_IDS.HEAT_PUMP,
  awd_need: ADVICE_TOPIC_IDS.ALL_WHEEL_DRIVE,
  leasing_vs_finance: ADVICE_TOPIC_IDS.LEASING_VS_FINANCING,
  range_winter: ADVICE_TOPIC_IDS.WINTER_RANGE,
  buy_vs_lease: ADVICE_TOPIC_IDS.LEASING_VS_FINANCING,
};

export function getAdviceTopicById(topicId) {
  const id = LEGACY_TOPIC_MAP[topicId] ?? topicId;
  return ADVICE_TOPICS.find((topic) => topic.id === id) ?? null;
}

export function listAdviceTopicIds() {
  return ADVICE_TOPICS.map((topic) => topic.id);
}

export function listAdviceTopicsForOpenAi() {
  return ADVICE_TOPICS.map((topic) => ({
    id: topic.id,
    label: topic.label,
    examples: topic.triggerExamples.slice(0, 3),
  }));
}
